FROM python:3.13.0

WORKDIR /app/api_gateway
COPY . /app/api_gateway

ENV PYTHONPATH=/app/api_gateway

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
