FROM python:3.13.0

WORKDIR /app/logging_service
COPY . /app/logging_service

ENV PYTHONPATH=/app/logging_service

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8004
CMD ["flask", "run", "--host=0.0.0.0","--port=8004"]

