FROM python:3.13.0

WORKDIR /app/user_service
COPY . /app/user_service

RUN pip install --no-cache-dir -r requirements.txt


ENV PYTHONPATH=/app/user_service

# Указываем команду по умолчанию
EXPOSE 8001
CMD ["flask", "run", "--host=0.0.0.0","--port=8001"]
