FROM python:3.13.0

WORKDIR /app/call_service
COPY . /app/call_service

RUN pip install --no-cache-dir -r requirements.txt


ENV PYTHONPATH=/app/call_service

# Указываем команду по умолчанию
EXPOSE 8002
CMD ["flask", "run", "--host=0.0.0.0","--port=8002"]